name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
  
  # Triggers the workflow on a schedule 
  schedule:
    - cron: '59 23 * * 6'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
      # Checks-out your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      # E2E & UI
      - name: E2E & UI
        run: cypress-io/github-action@v2

    
  # Upload videos
      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with: 
          path: cypress/videos
